{
 "title": "Demo Dashboard (ClickHouse with Altinity)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "SELECT DISTINCT ServiceName FROM otel.otel_traces"
   },
   {
    "name": "clickhouse",
    "query": "vertamedia-clickhouse-datasource"
   }
  ]
 },
 "panels": [
  { "title": "Requests Errors Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Rate for ${service} by span name",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "database": "otel",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$rateColumns(SpanName, count() c) FROM $table \n  WHERE ServiceName='$service'\n    AND SpanKind = 'SPAN_KIND_SERVER'\n  GROUP BY t, SpanName \n  ORDER BY t",
     "rawQuery": "/* grafana dashboard=Demo Dashboard, user=0 */\nSELECT (intDiv(toFloat64(Timestamp) * 1000, (1 * 1000)) * (1 * 1000)) as t, count() FROM otel.otel_traces WHERE Timestamp >= toDateTime64(1719319475, 3) AND Timestamp <= toDateTime64(1719320375, 3) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_traces"
    }
   ]
  },
  {
   "title": "Error Rate for ${service} by span name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "database": "otel",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$rateColumns(SpanName, count() c) FROM $table \n  WHERE ServiceName='$service'\n    AND SpanKind = 'SPAN_KIND_SERVER'\n    AND StatusCode = 'STATUS_CODE_ERROR'\n  GROUP BY t, SpanName \n  ORDER BY t",
     "rawQuery": "/* grafana dashboard=Demo Dashboard, user=0 */\nSELECT (intDiv(toFloat64(Timestamp) * 1000, (5 * 1000)) * (5 * 1000)) as t, count() FROM otel.otel_traces WHERE Timestamp >= toDateTime64(1719320457, 3) AND Timestamp <= toDateTime64(1719320757, 3) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_traces"
    }
   ]
  },
  {
   "title": "Latency for ${service}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "database": "otel",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "$columns(SpanName, avg(Duration/10e4) c) FROM $table \n  WHERE ServiceName='$service'\n    AND SpanKind = 'SPAN_KIND_SERVER'\n  GROUP BY t, SpanName \n  ORDER BY t",
     "rawQuery": "/* grafana dashboard=Demo Dashboard, user=0 */\nSELECT (intDiv(toFloat64(Timestamp) * 1000, (5 * 1000)) * (5 * 1000)) as t, count() FROM otel.otel_traces WHERE Timestamp >= toDateTime64(1719324638, 3) AND Timestamp <= toDateTime64(1719325538, 3) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_traces"
    }
   ]
  },
  { "title": "Application Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "${service} Log entries by Severity",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "database": "otel",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT count(), SeverityText FROM $table WHERE $timeFilter GROUP BY SeverityText",
     "rawQuery": "/* grafana dashboard=Demo Dashboard, user=0 */\nSELECT SeverityText, count() FROM otel.otel_logs WHERE Timestamp >= toDateTime64(1719425782, 3) AND Timestamp <= toDateTime64(1719426682, 3) GROUP BY SeverityText",
     "round": "0s",
     "table": "otel_logs"
    }
   ]
  },
  {
   "title": "${service} Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 10 },
   "targets": [
    {
     "database": "otel",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT * FROM $table WHERE $timeFilter AND ServiceName='$service'",
     "rawQuery": "/* grafana dashboard=Demo Dashboard, user=0 */\nSELECT (intDiv(toFloat64(Timestamp) * 1000, (1 * 1000)) * (1 * 1000)) as t, count() FROM otel.otel_logs WHERE Timestamp >= toDateTime64(1719425843, 3) AND Timestamp <= toDateTime64(1719426743, 3) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_logs"
    }
   ]
  },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Python services (CPU%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "database": "otel",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries AS t, max(cpu_utilization) as CPU, scope FROM\n(SELECT \n    TimeUnix,\n    toFloat64(TimeUnix) AS timestamp,\n    Attributes['type'] AS scope,\n    Value AS cpu_time,\n    any(cpu_time) OVER(PARTITION BY scope ORDER BY TimeUnix ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) as prev_cpu_time,\n    cpu_time-prev_cpu_time AS delta_cpu_time,\n    (timestamp - any(timestamp) OVER (PARTITION BY scope ORDER BY timestamp ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING)) AS interval_seconds,\n    if(delta_cpu_time > 0 and interval_seconds > 0, delta_cpu_time / interval_seconds*100, 0) AS cpu_utilization\nFROM otel.otel_metrics_sum \nWHERE TimeUnix >= ($from - 200) AND TimeUnix <= $to\nAND MetricName='process.runtime.cpython.cpu_time' \nAND ServiceName='$service'\nORDER BY TimeUnix ASC\n)\nWHERE TimeUnix >= ($from-100) AND TimeUnix <= $to\nGROUP BY t, scope\nORDER BY t, scope",
     "rawQuery": "/* grafana dashboard=Demo Dashboard, user=0 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) AS t, max(cpu_utilization) as CPU, scope FROM\n(SELECT \n    TimeUnix,\n    toFloat64(TimeUnix) AS timestamp,\n    Attributes['type'] AS scope,\n    Value AS cpu_time,\n    any(cpu_time) OVER(PARTITION BY scope ORDER BY TimeUnix ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) as prev_cpu_time,\n    cpu_time-prev_cpu_time AS delta_cpu_time,\n    (timestamp - any(timestamp) OVER (PARTITION BY scope ORDER BY timestamp ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING)) AS interval_seconds,\n    if(delta_cpu_time > 0 and interval_seconds > 0, delta_cpu_time / interval_seconds*100, 0) AS cpu_utilization\nFROM otel.otel_metrics_sum \nWHERE TimeUnix >= (1719336228 - 200) AND TimeUnix <= 1719336528\nAND MetricName='process.runtime.cpython.cpu_time' \nAND ServiceName='recommendationservice'\nORDER BY TimeUnix ASC\n)\nWHERE TimeUnix >= (1719336228-100) AND TimeUnix <= 1719336528\nGROUP BY t, scope\nORDER BY t, scope",
     "round": "0s",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Python services (Memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "database": "otel",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries AS t, max(bytes) as memory, scope FROM\n(SELECT \n    TimeUnix,\n    Value AS bytes,\n    Attributes['type'] AS scope\nFROM otel.otel_metrics_sum \nWHERE $timeFilter\nAND MetricName='process.runtime.cpython.memory' \nAND ServiceName='$service'\nORDER BY TimeUnix ASC\n)\nWHERE TimeUnix >= ($from-100) AND TimeUnix <= $to\nGROUP BY t, scope\nORDER BY t, scope",
     "rawQuery": "/* grafana dashboard=Demo Dashboard, user=0 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) AS t, max(Value) as memory, scope FROM\n(SELECT \n    TimeUnix,\n    Value AS bytes,\n    Attributes['type'] AS scope\nFROM otel.otel_metrics_sum \nWHERE TimeUnix >= toDateTime64(1719336188, 3) AND TimeUnix <= toDateTime64(1719336488, 3)\nAND MetricName='process.runtime.cpython.memory' \nAND ServiceName='recommendationservice'\nORDER BY TimeUnix ASC\n)\nWHERE TimeUnix >= (1719336188-100) AND TimeUnix <= 1719336488\nGROUP BY t, scope\nORDER BY t, scope",
     "round": "0s",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Recommendations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "database": "otel",
     "dateTimeColDataType": "TimeUnix",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT $timeSeries AS t, max(rate) as recomendations FROM\n(SELECT \n    TimeUnix,\n    toFloat64(TimeUnix) AS timestamp,\n    Value AS value,\n    any(value) OVER(ORDER BY TimeUnix ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) as prev_value,\n    value-prev_value AS delta,\n    (timestamp - any(timestamp) OVER (ORDER BY timestamp ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING)) AS interval_seconds,\n    if(delta > 0 and interval_seconds > 0, delta, 0) AS rate\nFROM otel.otel_metrics_sum \nWHERE TimeUnix >= ($from - 200) AND TimeUnix <= $to\nAND MetricName='app_recommendations_counter' \nAND ServiceName='$service'\nORDER BY TimeUnix ASC\n)\nWHERE TimeUnix >= ($from-100) AND TimeUnix <= $to\nGROUP BY t\nORDER BY t",
     "rawQuery": "/* grafana dashboard=Demo Dashboard, user=0 */\nSELECT (intDiv(toFloat64(TimeUnix) * 1000, (1 * 1000)) * (1 * 1000)) as t, count() FROM otel.otel_metrics_sum WHERE TimeUnix >= toDateTime64(1719335457, 3) AND TimeUnix <= toDateTime64(1719335757, 3) GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "otel_metrics_sum"
    }
   ]
  },
  {
   "title": "Quote Service batch span processor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(otel_trace_span_processor_spans{job=\"opentelemetry-demo/quoteservice\"}[2m])*120",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}